# Generated by Django 3.1.5 on 2021-05-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
